# Generated by Django 4.1 on 2022-08-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='Some String', max_length=100),
        ),
    ]
